"""add url to article

Revision ID: 8146b7bed457
Revises: f767124d9d81
Create Date: 2025-04-16 02:54:03.400277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8146b7bed457'
down_revision = 'f767124d9d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
